apiVersion: sagemaker.aws.amazon.com/v1
kind: HyperparameterTuningJob
metadata:
  name: tf-hpo
spec:
  region: us-east-2
  hyperParameterTuningJobConfig:
    strategy: Bayesian
    hyperParameterTuningJobObjective:
      type: Minimize
      metricName: tferror
    resourceLimits:
      maxNumberOfTrainingJobs: 10
      maxParallelTrainingJobs: 2
    parameterRanges:
      integerParameterRanges: []
      continuousParameterRanges: 
      - name: learning_rate
        minValue: '0.0001'
        maxValue: '0.01'
        scalingType: Auto
      categoricalParameterRanges: []
    trainingJobEarlyStoppingType: Auto
  trainingJobDefinition:
    staticHyperParameters:
      - name: model_dir
        value: "\"s3://BUCKET/hpo/hpo/model\""
      - name: sagemaker_job_name
        value: "\"tf-hpo\""
      - name: sagemaker_container_log_level
        value: "20"
      - name: sagemaker_enable_cloudwatch_metrics
        value: "false"
      - name: sagemaker_parameter_server_enabled
        value: "true"
      - name: sagemaker_program
        value: "\"tftab-lr.py\""
      - name: sagemaker_region
        value: "\"us-east-2\""
      - name: sagemaker_submit_directory
        value: "\"s3://BUCKET/hpo/source/sourcedir.tar.gz\""
    algorithmSpecification:
      trainingImage: 763104351884.dkr.ecr.us-east-2.amazonaws.com/tensorflow-training:2.1.0-gpu-py3
      trainingInputMode: File
      metricDefinitions:
        - name: tferror
          regex: "Loss=(.*?),"
    roleArn: arn:aws:iam::ACCOUNT:role/ROLE
    outputDataConfig:
      s3OutputPath: s3://BUCKET/kubeflow-hpo/
    resourceConfig:
      instanceCount: 1
      instanceType: ml.m5.xlarge
      volumeSizeInGB: 30
    stoppingCondition:
      maxRuntimeInSeconds: 86400
    inputDataConfig:
      - channelName: training
        dataSource:
          s3DataSource:
            s3DataType: S3Prefix
            s3Uri: s3://BUCKET/data/
            s3DataDistributionType: FullyReplicated
        compressionType: None
